[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "rheolopy"
version = "0.1.0"
description = "A package for geological rheology modeling and visualization"
authors = [{ name="Tilman May", email="tmay@gfz.de" }]
readme = "README.md"
license = { file="LICENSE" }
requires-python = ">=3.8"
dependencies = [
    "numpy",
    "pandas",
    "matplotlib",
    "cmcrameri"
]
[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"rheolopy" = ["config.ini", "database.json", "geotherm.csv"]