# Configuration file for process_exodus.py
#
# nx and ny after the filename are optional (auto-detected if omitted).
#INPUT_FILE: EXODUS process_rheology/AndesModel_SACI_vila_vp_rho_deep.e 
#RHEO_FILE: process_rheology/AndesModel_SACI_deep_rheology.ini
#ETA_BOUNDS: 1e18 1e25
#OUT_DIR: process_rheology/output
#RESOLUTION: 1000
#WORKERS: 0
