# Configuration file for process_exodus.py
#
#INPUT_FILE: EXODUS process_rheology/AlpsModel_mean.e 119 96
#RHEO_FILE: process_rheology/rheology_alps.ini
#ETA_BOUNDS: 1e18 1e25
#OUT_DIR: process_rheology/output alps_mean
#RESOLUTION: 1000
